-- 코드를 작성해주세요
SELECT i.ID, n.FISH_NAME, i.LENGTH
FROM FISH_INFO i
jOIN FISH_NAME_INFO n ON i.FISH_TYPE = n.FISH_TYPE
WHERE (n.FISH_TYPE, i.LENGTH) 
    IN (
        SELECT FISH_TYPE, MAX(LENGTH)
        FROM FISH_INFO
        GROUP BY FISH_TYPE )
order by i.id;